/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user with role and permissions */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register this device's push token (Expo or FCM) */
        post: operations["registerPushToken"];
        /** Stop push notifications to this account */
        delete: operations["removePushToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver profile, active vehicle and all vehicles */
        get: operations["getDriverProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Save driver setup (profile + active vehicle)
         * @description All fields optional. `car_model` and `plate` are required together the first time a vehicle is saved.
         */
        patch: operations["updateDriverProfile"];
        trace?: never;
    };
    "/driver/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application checklist, status, licence and documents */
        get: operations["getDriverOnboarding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/onboarding/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose what I offer */
        put: operations["putDriverServices"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/onboarding/licence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Driving licence details (an expired licence is rejected) */
        put: operations["putDriverLicence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/onboarding/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send the application for admin review (all required steps must be done) */
        post: operations["submitDriverApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload or replace a verification document (stored privately) */
        post: operations["uploadDriverDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/documents/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** The document file — only for its owner or users with verify-drivers (404 otherwise) */
        get: operations["getDriverDocumentFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My vehicles (active first) */
        get: operations["listVehicles"];
        put?: never;
        /** Add a vehicle (the first one becomes active) */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one of my vehicles */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        /** Edit one of my vehicles */
        patch: operations["updateVehicle"];
        trace?: never;
    };
    "/driver/vehicles/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make this the vehicle riders see (others become inactive) */
        post: operations["activateVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/vehicles/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload or replace one vehicle photo */
        post: operations["uploadVehiclePhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My ride rates for the active vehicle, the guardrails that apply, and a price preview */
        get: operations["getDriverRates"];
        /**
         * Set my ride rates (validated against the guardrails for my vehicle class)
         * @description Rates are snapshotted when a ride is requested, so changes never affect rides already quoted.
         */
        put: operations["putDriverRates"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Online/offline heartbeat with position (every 5–10 s while online) */
        post: operations["postDriverPresence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/ride-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open ride requests sent to me (pick or broadcast) */
        get: operations["listRideRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Online drivers near the pickup, each with their own quote for this trip */
        get: operations["getNearbyDrivers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price range and nearest ETA per vehicle class */
        post: operations["estimateRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My ride history (paginated) */
        get: operations["listMyRides"];
        put?: never;
        /** Request a ride from one driver (pick) or all nearby (broadcast) */
        post: operations["requestRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My current ride as rider or driver, or null */
        get: operations["getActiveRide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        /** Ride detail (rider or assigned driver only) */
        get: operations["getRide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel as rider or assigned driver (reason required) */
        post: operations["cancelRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a request (atomic — 409 if another driver won) */
        post: operations["acceptRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}/arrive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Driver is at the pickup */
        post: operations["arriveAtPickup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the trip with the rider's 4-digit PIN */
        post: operations["startRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the trip and record the payment method */
        post: operations["completeRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate the other party (once per ride) */
        post: operations["rateRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver applications by status, oldest submission first */
        get: operations["listDriverApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** Full application with documents, vehicles and prices */
        get: operations["getDriverApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers/{userId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending application (documents approved; riders get the driver role; push sent) */
        post: operations["verifyDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers/{userId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject with a reason, optionally per document */
        post: operations["rejectDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers/{userId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a driver (cannot go online or accept rides) */
        post: operations["suspendDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pricing guardrails, commission, radius and timeouts (defaults until saved) */
        get: operations["getRideSettings"];
        /** Update pricing guardrails and dispatch settings (partial updates allowed) */
        put: operations["putRideSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            id: number;
            name: string | null;
            email?: string | null;
            phone?: string | null;
            profile_image_url?: string | null;
            /** @enum {string} */
            roles: "superadmin" | "admin" | "user" | "driver";
            permissions: string[];
            location?: null | {
                id?: number;
                name?: string;
                city?: string;
            };
        };
        /** @enum {string} */
        VehicleClass: "moto" | "car" | "comfort" | "van";
        Vehicle: {
            id: number;
            class: components["schemas"]["VehicleClass"];
            /** @enum {string|null} */
            body_type?: "Sedan" | "SUV" | "Minivan" | "Pickup" | "Hatchback" | "Motorcycle" | null;
            make?: string | null;
            model: string;
            color?: string | null;
            year?: number | null;
            /** @description Normalised: uppercase, single spaces */
            plate: string;
            seats: number;
            amenities?: string[] | null;
            photos?: null | unknown[] | components["schemas"]["VehiclePhotos"];
            /** Format: date */
            insurance_expiry?: string | null;
            rental_price_day?: number | null;
            rental_caution?: number | null;
            is_active: boolean;
        };
        /** @enum {string} */
        DriverService: "ride" | "hire" | "private_seat" | "rental";
        /** @enum {string} */
        DriverDocumentType: "licence_front" | "licence_back" | "national_id" | "selfie" | "insurance";
        DriverOnboarding: {
            /** @enum {string} */
            status: "draft" | "pending" | "verified" | "rejected" | "suspended";
            can_submit: boolean;
            steps: {
                /** @enum {string} */
                key: "services" | "profile" | "licence" | "documents" | "vehicle" | "rates";
                done: boolean;
                required: boolean;
            }[];
            services: components["schemas"]["DriverService"][];
            rejection_reason: string | null;
            licence: {
                licence_no: string | null;
                licence_categories: string[];
                /** Format: date */
                licence_expiry: string | null;
                national_id_no: string | null;
            };
            documents: {
                type: components["schemas"]["DriverDocumentType"];
                required: boolean;
                /** @enum {string} */
                status: "missing" | "uploaded" | "approved" | "rejected";
                rejection_reason: string | null;
                id: number | null;
                /** @description Send the bearer token when loading it */
                file_url: string | null;
                /** Format: date-time */
                updated_at: string | null;
            }[];
        };
        DriverApplication: {
            user: {
                id: number;
                name: string | null;
                email: string | null;
                phone: string | null;
                role: string;
                profile_image_url?: string | null;
            };
            /** @enum {string} */
            status: "pending" | "verified" | "rejected" | "suspended";
            /** Format: date-time */
            submitted_at: string | null;
            /** Format: date-time */
            verified_at: string | null;
            rejection_reason: string | null;
            services: components["schemas"]["DriverService"][];
            licence: components["schemas"]["DriverOnboarding"]["licence"];
            checklist: components["schemas"]["DriverOnboarding"]["steps"];
            documents: components["schemas"]["DriverOnboarding"]["documents"];
            vehicles: components["schemas"]["Vehicle"][];
            rates: components["schemas"]["DriverRates"][];
        };
        /** @description Public URLs per photo slot; `front` is required before going online */
        VehiclePhotos: {
            front?: string;
            side?: string;
            interior?: string;
            luggage?: string;
        };
        VehicleInput: {
            class?: components["schemas"]["VehicleClass"];
            /** @enum {string|null} */
            body_type?: "Sedan" | "SUV" | "Minivan" | "Pickup" | "Hatchback" | "Motorcycle" | null;
            make?: string | null;
            model?: string;
            color?: string | null;
            year?: number | null;
            plate?: string;
            /** @description Moto: at most 2 */
            seats?: number;
            amenities?: string[] | null;
            /** Format: date */
            insurance_expiry?: string;
        };
        DriverProfileResponse: {
            user: {
                id: number;
                name: string | null;
                email: string | null;
                phone: string | null;
            };
            profile: null | {
                services: ("ride" | "hire" | "private_seat" | "rental")[];
                allowed_zones: string[];
                docs_url: string | null;
                /** @enum {string} */
                verification_status: "pending" | "verified" | "rejected" | "suspended";
                rating_avg: number;
                trips_count: number;
            };
            vehicle: null | components["schemas"]["Vehicle"];
            vehicles: components["schemas"]["Vehicle"][];
        };
        DriverProfileUpdate: {
            name?: string;
            fcm_token?: string;
            services?: ("ride" | "hire" | "private_seat" | "rental")[];
            allowed_zones?: string[];
            /** Format: uri */
            docs_url?: string | null;
            car_model?: string;
            plate?: string;
            /** @enum {string} */
            car_type?: "Sedan" | "SUV" | "Minivan" | "Pickup";
            seats?: number;
            amenities?: string[];
            /** Format: date */
            insurance_expiry?: string | null;
            price_day?: number | null;
            caution?: number | null;
        };
        /** @description RIDE_HAILING_PLAN.md §3.1 */
        DriverRates: {
            vehicle_id?: number;
            base_fare: number;
            per_km: number;
            /** @default 0 */
            per_min: number;
            min_fare: number;
            /** @default 2 */
            pickup_free_km: number;
            /** @default 0 */
            pickup_per_km: number;
            /** @default 1 */
            night_multiplier: number;
        };
        DriverRatesResponse: {
            vehicle: null | {
                id: number;
                class: components["schemas"]["VehicleClass"];
                model: string;
                plate: string;
            };
            rates: null | components["schemas"]["DriverRates"];
            /** @description True when guardrails changed and these rates must be updated */
            out_of_band: boolean;
            guardrails: {
                per_km_min: number;
                per_km_max: number;
                min_fare_max: number;
            };
            service_fee: {
                /** @enum {string} */
                type: "flat" | "percent";
                amount: number;
            };
            commission_pct: number;
            /** @description Daytime price for sample trips (no pickup surcharge) */
            preview: {
                km: number;
                driver_fare: number;
                service_fee: number;
                total: number;
            }[];
        };
        TripPoints: {
            pickup: components["schemas"]["Place"];
            dropoff: components["schemas"]["Place"];
        };
        Place: {
            lat: number;
            lng: number;
            address?: string | null;
        };
        NearbyDriver: {
            driver_id: number;
            /** @description First name + initial */
            name: string;
            photo?: string | null;
            rating: number;
            trips?: number;
            eta_min: number;
            distance_km: number;
            /** @description What the rider pays for this trip, incl. Jali fee */
            quote: number;
            per_km?: number;
            vehicle: {
                class?: components["schemas"]["VehicleClass"];
                model?: string;
                color?: string | null;
                seats?: number;
                amenities?: string[];
            };
            /** @description Rounded to ~100 m until a ride is accepted */
            approx_location: {
                lat?: number;
                lng?: number;
            };
        };
        /** @enum {string} */
        RideStatus: "requested" | "accepted" | "arrived" | "in_progress" | "completed" | "expired" | "cancelled_by_rider" | "cancelled_by_driver";
        Ride: {
            id: number;
            status: components["schemas"]["RideStatus"];
            /** @enum {string} */
            mode: "pick" | "broadcast";
            vehicle_class: components["schemas"]["VehicleClass"];
            pickup: components["schemas"]["Place"];
            dropoff: components["schemas"]["Place"];
            est_distance_km?: number;
            est_minutes?: number;
            quoted_fare: number;
            final_fare?: number | null;
            service_fee?: number;
            /** @description Only present for the rider */
            start_pin?: string | null;
            /** @enum {string|null} */
            payment_method?: "cash" | "momo" | null;
            driver?: null | {
                id?: number;
                name?: string;
                photo?: string | null;
                rating?: number;
                /** @description After accept only */
                phone?: string | null;
                location?: {
                    lat?: number;
                    lng?: number;
                    heading?: number | null;
                } | null;
                vehicle?: components["schemas"]["Vehicle"];
            };
            /** Format: date-time */
            requested_at?: string;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            arrived_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            cancelled_at?: string | null;
        };
        /** @description What an online driver sees before accepting (no exact pickup, no phone) */
        RideRequestCard: {
            ride_id: number;
            pickup_area: string;
            dropoff_area: string;
            trip_km: number;
            pickup_km: number;
            /** @description Driver's quote minus commission */
            earnings: number;
            rider_rating?: number | null;
            /** @enum {string} */
            payment_method?: "cash" | "momo";
            /** Format: date-time */
            expires_at: string;
        };
        /** @description platform_settings `rides` (RIDE_HAILING_PLAN.md §3.3). Responses always contain every field; PUT accepts any subset. */
        RideSettings: {
            vehicle_classes: {
                [key: string]: {
                    per_km_min?: number;
                    per_km_max?: number;
                    min_fare_max?: number;
                };
            };
            /** @default 1.3 */
            road_factor: number;
            commission_pct: number;
            service_fee: {
                /** @enum {string} */
                type?: "flat" | "percent";
                amount?: number;
            };
            /** @default 5 */
            nearby_radius_km: number;
            /** @default 60 */
            presence_ttl_sec: number;
            /** @default 30 */
            request_timeout_sec: number;
        };
        /** @description Any subset of RideSettings; a vehicle class must be sent complete */
        RideSettingsUpdate: {
            vehicle_classes?: {
                [key: string]: {
                    per_km_min: number;
                    per_km_max: number;
                    min_fare_max: number;
                };
            };
            road_factor?: number;
            commission_pct?: number;
            service_fee?: {
                /** @enum {string} */
                type: "flat" | "percent";
                amount: number;
            };
            nearby_radius_km?: number;
            presence_ttl_sec?: number;
            request_timeout_sec?: number;
        };
    };
    responses: {
        /** @description OK */
        Message: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                    message?: string;
                };
            };
        };
        /** @description Missing permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                };
            };
        };
        /** @description Not found (or not yours) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description Invalid state transition or resource already taken */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: {
        UserId: number;
        DocumentId: number;
        VehicleId: number;
        RideId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    registerPushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example ExponentPushToken[xxxxxxxx] */
                    token: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Message"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    removePushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Message"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDriverProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateDriverProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverProfileUpdate"];
            };
        };
        responses: {
            /** @description Saved profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getDriverOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOnboarding"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putDriverServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    services: components["schemas"]["DriverService"][];
                };
            };
        };
        responses: {
            /** @description Updated checklist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOnboarding"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    putDriverLicence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    licence_no: string;
                    licence_categories: ("A" | "B" | "C" | "C1" | "D" | "D1" | "E" | "F")[];
                    /** Format: date */
                    licence_expiry: string;
                    national_id_no?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated checklist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOnboarding"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    submitDriverApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted — status becomes pending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOnboarding"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    uploadDriverDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    type: components["schemas"]["DriverDocumentType"];
                    /**
                     * Format: binary
                     * @description jpg/png/webp/heic/pdf, max 10 MB
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Updated checklist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOnboarding"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getDriverDocumentFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": unknown;
                    "application/pdf": unknown;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listVehicles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleInput"] & unknown;
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Message"];
            404: components["responses"]["NotFound"];
        };
    };
    updateVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleInput"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    activateVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadVehiclePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @enum {string} */
                    slot: "front" | "side" | "interior" | "luggage";
                    /**
                     * Format: binary
                     * @description jpg/png/webp/heic, max 8 MB
                     */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getDriverRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRatesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putDriverRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverRates"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRatesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    postDriverPresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    online: boolean;
                    lat?: number;
                    lng?: number;
                    heading?: number | null;
                    vehicle_id?: number;
                };
            };
        };
        responses: {
            /** @description Presence stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        online?: boolean;
                        /** @description Why the driver cannot go online (unverified, no rates, insurance expired, commission owed…) */
                        blocked_reasons?: string[];
                    };
                };
            };
        };
    };
    listRideRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequestCard"][];
                };
            };
        };
    };
    getNearbyDrivers: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                dest_lat: number;
                dest_lng: number;
                class?: components["schemas"]["VehicleClass"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyDriver"][];
                };
            };
        };
    };
    estimateRide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPoints"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        class: components["schemas"]["VehicleClass"];
                        available: boolean;
                        min_quote?: number | null;
                        max_quote?: number | null;
                        nearest_eta_min?: number | null;
                    }[];
                };
            };
        };
    };
    listMyRides: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Ride"][];
                        next_page?: number | null;
                    };
                };
            };
        };
    };
    requestRide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPoints"] & {
                    /** @enum {string} */
                    mode: "pick" | "broadcast";
                    class: components["schemas"]["VehicleClass"];
                    /** @description Required when mode=pick */
                    driver_id?: number;
                    /** @description Broadcast only */
                    max_fare?: number;
                    /** @enum {string} */
                    payment_method?: "cash" | "momo";
                };
            };
        };
        responses: {
            /** @description Ride requested */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getActiveRide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"] | null;
                };
            };
        };
    };
    getRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    cancelRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    acceptRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    arriveAtPickup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    startRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pin: string;
                };
            };
        };
        responses: {
            /** @description In progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    completeRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    payment_method: "cash" | "momo";
                };
            };
        };
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    rateRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    stars: number;
                    tags?: string[];
                    comment?: string;
                };
            };
        };
        responses: {
            201: components["responses"]["Message"];
            409: components["responses"]["Conflict"];
        };
    };
    listDriverApplications: {
        parameters: {
            query?: {
                status?: "pending" | "verified" | "rejected" | "suspended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_id: number;
                        name: string | null;
                        phone: string | null;
                        services: components["schemas"]["DriverService"][];
                        /** @enum {string} */
                        status: "pending" | "verified" | "rejected" | "suspended";
                        /** Format: date-time */
                        submitted_at: string | null;
                    }[];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getDriverApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverApplication"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverApplication"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                    /** @description Document type → reason, e.g. {"selfie": "Face not visible"} */
                    documents?: {
                        [key: string]: string;
                    };
                };
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverApplication"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    suspendDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverApplication"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getRideSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putRideSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideSettingsUpdate"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
}
